name: Custom_Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Extract versionName from build.gradle
        id: get_version
        run: |
          version_name=$(grep -m 1 -E '\s+versionName "([^"]+)"' ./app/build.gradle | sed -r 's/.*versionName "([^"]+)"/\1/')
          echo "version_name=${version_name}" >> $GITHUB_OUTPUT

      - name: Build APK (apt-android-7)
        run: |
          export TERMUX_PACKAGE_VARIANT="apt-android-7"
          export TERMUX_APP_VERSION_NAME="${{ steps.get_version.outputs.version_name }}"
          export TERMUX_APK_VERSION_TAG="v${TERMUX_APP_VERSION_NAME}-${TERMUX_PACKAGE_VARIANT}-github-debug"

          echo "Building version: $TERMUX_APK_VERSION_TAG"
          ./gradlew assembleDebug || { echo "Build failed"; exit 1; }

      - name: Upload APK (arm64-v8a only)
        uses: actions/upload-artifact@v4
        with:
          name: termux-app_arm64-v8a
          path: |
            app/build/outputs/apk/debug/*arm64-v8a.apk
